import "@/app/globals.css";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import { Montserrat } from "next/font/google";
const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
          <body
            className={
              fontFamily.className +
              " h-screen flex flex-col overflow-hidden bg-background text-white items-stretch p-2"
            }
          >
            <div className="grid grid-cols-10 gap-2">
              <div className="flex flex-col h-[87vh] col-span-8 overflow-auto rounded-lg bg-paper-700">
                <main className="mx-8 my-4">{children}</main>
              </div>
            </div>
          </body>
      </NextAuthProvider>
    </html>
  );
}
